/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author gabriel
 */
public class JAcoes extends javax.swing.JFrame {

    /**
     * Creates new form JAcoes
     */
    public JAcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpArea = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiBaseAtivos = new javax.swing.JMenuItem();
        jmiCarteiras = new javax.swing.JMenuItem();
        jmiConfiguracoes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jmGraficos = new javax.swing.JMenu();
        jmAjuda = new javax.swing.JMenu();
        jmiTutorial = new javax.swing.JMenuItem();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAcoes");

        jmArquivo.setMnemonic('a');
        jmArquivo.setText("Arquivo");

        jmiBaseAtivos.setMnemonic('b');
        jmiBaseAtivos.setText("Base de ativos");
        jmiBaseAtivos.setToolTipText("");
        jmArquivo.add(jmiBaseAtivos);

        jmiCarteiras.setMnemonic('c');
        jmiCarteiras.setText("Carteiras");
        jmArquivo.add(jmiCarteiras);

        jmiConfiguracoes.setMnemonic('c');
        jmiConfiguracoes.setText("Configurações");
        jmiConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConfiguracoesActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiConfiguracoes);
        jmArquivo.add(jSeparator1);

        jmiSair.setMnemonic('r');
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSair);

        menuBar.add(jmArquivo);

        jmGraficos.setMnemonic('g');
        jmGraficos.setText("Gráficos");
        jmGraficos.setEnabled(false);
        menuBar.add(jmGraficos);

        jmAjuda.setMnemonic('u');
        jmAjuda.setText("Ajuda");

        jmiTutorial.setMnemonic('t');
        jmiTutorial.setText("Tutorial");
        jmAjuda.add(jmiTutorial);

        jmiSobre.setMnemonic('s');
        jmiSobre.setText("Sobre");
        jmAjuda.add(jmiSobre);

        menuBar.add(jmAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpArea, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpArea, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConfiguracoesActionPerformed
        // não foi criado
        if (jConfiguracoes == null) {
            jConfiguracoes = new JConfiguracoes();
            jdpArea.add(jConfiguracoes);
        }
        jConfiguracoes.setVisible(true);
    }//GEN-LAST:event_jmiConfiguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAcoes().setVisible(true);
            }
        });
    }

    // Variaveis
    private JConfiguracoes jConfiguracoes;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpArea;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmGraficos;
    private javax.swing.JMenuItem jmiBaseAtivos;
    private javax.swing.JMenuItem jmiCarteiras;
    private javax.swing.JMenuItem jmiConfiguracoes;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiTutorial;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
