/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.DefaultListModel;

/**
 *
 * @author gabriel
 */
public class JBaseAtivos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JBaseAtivos
     */
    public JBaseAtivos() {
        initComponents();
        dlmAtivos = new DefaultListModel();
        jlAtivos.setModel(dlmAtivos);
    }

    public void setDiretorio(String diretorio) {
        this.diretorio = diretorio;
        dlmAtivos.clear();
        incluirAtivos();
    }
    
    private String getSimbolo(String nome){
        // PETR4.csv => ["PETR4", "csv"]
        String [] tokens = nome.split("\\.");
        return tokens[0];
    }
    
    private void incluirAtivos() {
        File dir = new File(this.diretorio);
        File [] arquivos = dir.listFiles();
        for (File arquivo : arquivos) {
            dlmAtivos.addElement(getSimbolo(arquivo.getName()));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlAtivos = new javax.swing.JList<>();

        setResizable(true);
        setTitle("Ativos");

        jlAtivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlAtivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlAtivos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variáveis
    private DefaultListModel dlmAtivos;
    private String diretorio;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlAtivos;
    // End of variables declaration//GEN-END:variables
}
