/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFileChooser;

/**
 *
 * @author gabriel
 */
public class JConfiguracoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JConfiguracoes
     */
    public JConfiguracoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcDiretorio = new javax.swing.JFileChooser();
        jlDiretorio = new javax.swing.JLabel();
        jtfDiretorio = new javax.swing.JTextField();
        jbEscolherDiretorio = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        jfcDiretorio.setCurrentDirectory(new java.io.File("/home/gabriel/Documentos/010-ifsp/00-aula/bcc-lpo3/ativos"));
        jfcDiretorio.setDialogTitle("");
        jfcDiretorio.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Configurações");

        jlDiretorio.setText("Diretório:");

        jtfDiretorio.setEditable(false);

        jbEscolherDiretorio.setText("Escolher diretório ...");
        jbEscolherDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEscolherDiretorioActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDiretorio)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEscolherDiretorio)
                        .addGap(53, 53, 53)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDiretorio)
                    .addComponent(jtfDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEscolherDiretorio)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jtfDiretorio.setText(diretorioAnterior);
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEscolherDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEscolherDiretorioActionPerformed
        // guardo o diretorio anterior
        diretorioAnterior = jtfDiretorio.getText();
        
        int retorno = jfcDiretorio.showOpenDialog(this);
        
        if(retorno == JFileChooser.APPROVE_OPTION ){
            jtfDiretorio.setText(jfcDiretorio.getSelectedFile().getAbsolutePath() + "/");
        } else {
            jtfDiretorio.setText(diretorioAnterior);
        }
        
    }//GEN-LAST:event_jbEscolherDiretorioActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        this.setVisible(false);        
    }//GEN-LAST:event_jbSalvarActionPerformed

    public String getDiretorioAtual(){
        return jtfDiretorio.getText();
    }
    
    
    // Variaveis - atributos
    private String diretorioAnterior;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEscolherDiretorio;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JFileChooser jfcDiretorio;
    private javax.swing.JLabel jlDiretorio;
    private javax.swing.JTextField jtfDiretorio;
    // End of variables declaration//GEN-END:variables
}
